import type { MenuItem, Testimonial, CateringPackage, LoyaltyTier, AdminOrder, AdminCustomer } from "./types";
import bbqImg from "@/assets/signature-bbq.jpg";
import shawarmaImg from "@/assets/signature-shawarma.jpg";
import platterImg from "@/assets/signature-platter.jpg";
import kebabImg from "@/assets/menu-kebab.jpg";
import friesImg from "@/assets/menu-fries.jpg";
import drinkImg from "@/assets/menu-drink.jpg";
import hummusImg from "@/assets/menu-hummus.jpg";
import wingsImg from "@/assets/menu-wings.jpg";

export const MENU: MenuItem[] = [
  {
    id: "bbq-1",
    name: "Inferno Half Chicken",
    description: "Half chicken brined 24 hours, slow-smoked over apple wood, finished with our signature ember glaze.",
    price: 449,
    category: "bbq",
    heatLevel: 4, smokeLevel: 5,
    calories: 680,
    ingredients: ["Half chicken", "Apple wood smoke", "Ember glaze", "Sea salt", "Cracked pepper"],
    cookingMethod: "Low & Slow Smoked",
    cookingTime: "4h 30m",
    pairing: "Smoked Old Fashioned",
    recommendedCombo: "+ Burnt Garlic Fries",
    image: bbqImg,
  },
  {
    id: "bbq-2",
    name: "Charcoal Tikka Skewers",
    description: "Hand-cut thigh chunks marinated in yogurt and 11 spices, fired over white-hot charcoal.",
    price: 329,
    category: "bbq",
    heatLevel: 3, smokeLevel: 4,
    calories: 520,
    ingredients: ["Chicken thigh", "Hung yogurt", "Kashmiri chili", "Garam masala", "Mustard oil"],
    cookingMethod: "Open Charcoal",
    cookingTime: "18m",
    pairing: "Mint Cooler",
    recommendedCombo: "+ Saj Bread",
    image: kebabImg,
  },
  {
    id: "bbq-3",
    name: "Hellfire Wings",
    description: "Double-fried then tossed in our scorpion-chili honey glaze. Sign the waiver.",
    price: 289,
    category: "bbq",
    heatLevel: 5, smokeLevel: 2,
    calories: 580,
    ingredients: ["Chicken wings", "Scorpion chili", "Wildflower honey", "Smoked paprika"],
    cookingMethod: "Smoked + Flash Fried",
    cookingTime: "22m",
    pairing: "Hibiscus Iced Tea",
    recommendedCombo: "+ Cool Garlic Sauce",
    image: wingsImg,
  },
  {
    id: "bbq-4",
    name: "Pitmaster Platter",
    description: "Half chicken, four skewers, smoked pita, pickles, two house sauces. Built to share. Or not.",
    price: 749,
    category: "bbq",
    heatLevel: 3, smokeLevel: 5,
    calories: 1240,
    ingredients: ["Half chicken", "4 skewers", "Pita", "Pickles", "Garlic sauce", "Harissa"],
    cookingMethod: "Mixed Grill",
    cookingTime: "30m",
    pairing: "Smoked Lemonade",
    recommendedCombo: "Serves 2",
    image: platterImg,
  },
  {
    id: "sh-1",
    name: "Classic Charcoal Shawarma",
    description: "Spit-grilled chicken shaved thin, garlic toum, pickled turnip, in warm saj bread.",
    price: 229,
    category: "shawarma",
    heatLevel: 2, smokeLevel: 4,
    calories: 540,
    ingredients: ["Chicken", "Toum", "Pickled turnip", "Saj bread", "Sumac onions"],
    cookingMethod: "Vertical Spit",
    cookingTime: "12m",
    pairing: "Ayran",
    recommendedCombo: "+ Garlic Fries",
    image: shawarmaImg,
  },
  {
    id: "sh-2",
    name: "Spicy BBQ Shawarma",
    description: "BBQ-glazed chicken, harissa mayo, crisp slaw, jalapeños. Smoke meets street.",
    price: 259,
    category: "shawarma",
    heatLevel: 4, smokeLevel: 4,
    calories: 590,
    ingredients: ["BBQ chicken", "Harissa mayo", "Slaw", "Jalapeños", "Pita"],
    cookingMethod: "Spit + Grill",
    cookingTime: "14m",
    pairing: "Smoked Cola",
    recommendedCombo: "+ Hellfire Wings",
    image: shawarmaImg,
  },
  {
    id: "sh-3",
    name: "The Pitmaster Wrap",
    description: "Brisket-style smoked thigh, melted halloumi, charred onions, house chili oil.",
    price: 299,
    category: "shawarma",
    heatLevel: 3, smokeLevel: 5,
    calories: 720,
    ingredients: ["Smoked thigh", "Halloumi", "Charred onion", "Chili oil", "Saj"],
    cookingMethod: "Smoked + Wrapped",
    cookingTime: "16m",
    pairing: "House Mint Tea",
    recommendedCombo: "+ Hummus Bowl",
    image: shawarmaImg,
  },
  {
    id: "sh-4",
    name: "Volcano Shawarma Bowl",
    description: "All the shawarma. No bread. Smoked rice, slaw, double sauce, optional fire.",
    price: 279,
    category: "shawarma",
    heatLevel: 4, smokeLevel: 4,
    calories: 640,
    ingredients: ["Smoked rice", "Chicken", "Slaw", "Tahini", "Harissa", "Pickles"],
    cookingMethod: "Bowl Assembly",
    cookingTime: "10m",
    pairing: "Pomegranate Cooler",
    recommendedCombo: "Carb-conscious",
    image: platterImg,
  },
  {
    id: "side-1",
    name: "Burnt Garlic Fries",
    description: "Hand-cut, double-fried, tossed in burnt garlic, parsley, and smoked salt.",
    price: 149,
    category: "sides",
    heatLevel: 1, smokeLevel: 2,
    calories: 420,
    ingredients: ["Potato", "Burnt garlic", "Parsley", "Smoked salt"],
    cookingMethod: "Double Fried",
    cookingTime: "8m",
    pairing: "Anything",
    recommendedCombo: "+ Garlic Aioli",
    image: friesImg,
  },
  {
    id: "side-2",
    name: "Smoked Hummus Bowl",
    description: "Chickpeas smoked in-house, tahini, lemon, olive oil, warm saj.",
    price: 179,
    category: "sides",
    heatLevel: 1, smokeLevel: 3,
    calories: 380,
    ingredients: ["Chickpeas", "Tahini", "Lemon", "Olive oil", "Saj"],
    cookingMethod: "Smoked + Whipped",
    cookingTime: "10m",
    pairing: "Mint Lemonade",
    recommendedCombo: "+ Extra Saj",
    image: hummusImg,
  },
  {
    id: "drink-1",
    name: "Smoked Old Fashioned",
    description: "Charcoal-smoked lemonade, brown sugar, orange peel. Zero proof, full ceremony.",
    price: 159,
    category: "drinks",
    heatLevel: 1, smokeLevel: 4,
    calories: 140,
    ingredients: ["Lemonade", "Brown sugar", "Orange", "Charcoal smoke"],
    cookingMethod: "Glass Smoked",
    cookingTime: "3m",
    pairing: "Inferno Half Chicken",
    recommendedCombo: "Signature",
    image: drinkImg,
  },
  {
    id: "drink-2",
    name: "Hibiscus Ember",
    description: "Hibiscus, ginger, chili, lime. Sweet up front. Slow burn after.",
    price: 119,
    category: "drinks",
    heatLevel: 2, smokeLevel: 1,
    calories: 90,
    ingredients: ["Hibiscus", "Ginger", "Bird's eye chili", "Lime"],
    cookingMethod: "Cold Brew",
    cookingTime: "—",
    pairing: "Hellfire Wings",
    recommendedCombo: "Refreshing",
    image: drinkImg,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  { id: "t1", quote: "Best shawarma I've had outside Beirut. The smoke is real.", name: "Aarav K.", handle: "@aarav.eats", flame: 5 },
  { id: "t2", quote: "That hellfire wing nearly took me out. Worth it.", name: "Priya M.", handle: "@spicegirl.blr", flame: 5 },
  { id: "t3", quote: "Catered our wedding. Guests still won't shut up about it.", name: "Rohan & Tara", handle: "@rohantara", flame: 5 },
  { id: "t4", quote: "I drove across town. I'd drive across the country.", name: "Vikram S.", handle: "@vikfoodlog", flame: 5 },
  { id: "t5", quote: "Charcoal hits different. This is not restaurant food. This is craft.", name: "Meera D.", handle: "@meeradines", flame: 4 },
];

export const CATERING: CateringPackage[] = [
  {
    id: "spark",
    name: "Spark Pack",
    tagline: "For the intimate fire",
    guests: "Up to 50 guests",
    price: "From ₹24,999",
    duration: "3 hour service",
    features: ["2 menu items", "Live charcoal station", "Disposable serveware", "1 pitmaster on-site", "Setup + breakdown"],
  },
  {
    id: "inferno",
    name: "Inferno Pack",
    tagline: "Full force, full menu",
    guests: "Up to 150 guests",
    price: "From ₹74,999",
    duration: "5 hour service + setup",
    features: ["Full menu access", "Live grill + spit", "Premium serveware", "2 pitmasters + 2 servers", "Branded signage", "Free 30-min extension"],
    highlight: true,
  },
  {
    id: "pitmaster",
    name: "Pitmaster Pack",
    tagline: "Total event production",
    guests: "Custom — 150+",
    price: "Quoted to scale",
    duration: "Full event",
    features: ["Unlimited menu", "Dedicated event manager", "Branded truck on-site", "Custom menu development", "Full staff (chefs, servers, runners)", "Event-day photography"],
  },
];

export const TIERS: LoyaltyTier[] = [
  { id: "spark", name: "Spark", range: "0 – 500 pts", min: 0, max: 500, perks: ["Welcome reward", "Birthday treat", "Members-only menu drops"] },
  { id: "coal", name: "Coal", range: "501 – 1,500 pts", min: 501, max: 1500, perks: ["All Spark perks", "Free side every 5th order", "Skip-the-line pass"] },
  { id: "flame", name: "Flame", range: "1,501 – 3,000 pts", min: 1501, max: 3000, perks: ["All Coal perks", "Free wings monthly", "Early menu access"] },
  { id: "inferno", name: "Inferno", range: "3,001 – 6,000 pts", min: 3001, max: 6000, perks: ["All Flame perks", "Free signature item monthly", "Invite to Pitmaster nights"] },
  { id: "pitmaster", name: "Pitmaster", range: "6,001+ pts", min: 6001, max: 10000, perks: ["All Inferno perks", "Free catering tasting", "Name on the truck", "Lifetime VIP"] },
];

export const ORDERS: AdminOrder[] = [
  { id: "GL-2841", customer: "Aarav K.", items: "Inferno Half Chicken, Burnt Garlic Fries", status: "preparing", time: "6:42 PM", total: 598 },
  { id: "GL-2842", customer: "Priya M.", items: "Hellfire Wings x2", status: "ready", time: "6:38 PM", total: 578 },
  { id: "GL-2843", customer: "Vikram S.", items: "Pitmaster Platter, Smoked Old Fashioned", status: "completed", time: "6:31 PM", total: 908 },
  { id: "GL-2844", customer: "Meera D.", items: "Classic Shawarma, Hummus Bowl", status: "preparing", time: "6:45 PM", total: 408 },
  { id: "GL-2845", customer: "Rohan T.", items: "Volcano Bowl, Hibiscus Ember", status: "completed", time: "6:20 PM", total: 398 },
  { id: "GL-2846", customer: "Anita J.", items: "Spicy BBQ Shawarma", status: "cancelled", time: "6:15 PM", total: 259 },
];

export const CUSTOMERS: AdminCustomer[] = [
  { id: "C-001", name: "Aarav Khanna", visits: 28, tier: "Inferno", lastOrder: "Today" },
  { id: "C-002", name: "Priya Menon", visits: 15, tier: "Flame", lastOrder: "Today" },
  { id: "C-003", name: "Vikram Shah", visits: 42, tier: "Pitmaster", lastOrder: "Today" },
  { id: "C-004", name: "Meera Dutt", visits: 9, tier: "Coal", lastOrder: "Yesterday" },
  { id: "C-005", name: "Rohan Tata", visits: 6, tier: "Coal", lastOrder: "3 days ago" },
  { id: "C-006", name: "Anita Joshi", visits: 3, tier: "Spark", lastOrder: "1 week ago" },
];

export const CHART_DAILY = [
  { day: "Mon", orders: 64, revenue: 28400 },
  { day: "Tue", orders: 72, revenue: 31200 },
  { day: "Wed", orders: 81, revenue: 35800 },
  { day: "Thu", orders: 95, revenue: 42100 },
  { day: "Fri", orders: 132, revenue: 61500 },
  { day: "Sat", orders: 168, revenue: 78900 },
  { day: "Sun", orders: 141, revenue: 65200 },
];

export const TOP_ITEMS = [
  { name: "Inferno Half Chicken", sold: 184 },
  { name: "Classic Shawarma", sold: 167 },
  { name: "Pitmaster Wrap", sold: 142 },
  { name: "Hellfire Wings", sold: 128 },
  { name: "Burnt Garlic Fries", sold: 119 },
];
